name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        id: test
        run: python -m unittest discover tests
        # Fail the workflow if tests fail
        continue-on-error: false

      - name: Deploy to Heroku
        if: ${{ steps.test.outcome == 'success' }}
        run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
